spring:
  security:
    oauth2:
      client:
        registration:
          kako:
            client_id:
            client_secret:
          naver:
            client_id:
            client_secret:
          google:
            client_id:
            client_secret:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  application:
      name: world

  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
